name: Deploy Payload App

on:
    push:
        branches: ["main"]
    workflow_dispatch:

env:
    AWS_REGION: ap-southeast-2
    ECR_REPOSITORY: payload-dev
    CLUSTER_NAME: payload-dev-cluster
    SERVICE_NAME: payload-dev-service

jobs:
    deploy:
        name: Build → Push → Deploy ECS
        runs-on: ubuntu-latest

        permissions:
            id-token: write
            contents: read

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Configure AWS credentials (OIDC)
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                  aws-region: ${{ env.AWS_REGION }}

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2

            - name: Build Docker image
              env:
                  ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
              run: |
                  TAG=${GITHUB_SHA::7}
                  IMAGE="$ECR_REGISTRY/$ECR_REPOSITORY:$TAG"

                  echo "Building image $IMAGE"
                  docker build -t "$IMAGE" .

                  echo "Pushing image..."
                  docker push "$IMAGE"

                  echo "IMAGE=$IMAGE" >> $GITHUB_ENV

            - name: Update ECS Task Definition
              id: taskdef
              run: |
                  TASK_DEF_JSON=$(aws ecs describe-task-definition \
                     --task-definition payload-dev-task \
                     --query "taskDefinition" --output json)

                  NEW_TASK_DEF=$(echo "$TASK_DEF_JSON" | jq \
                    --arg IMAGE "$IMAGE" \
                    '.containerDefinitions[0].image = $IMAGE')

                  echo "$NEW_TASK_DEF" > new-taskdef.json

                  REGISTERED=$(aws ecs register-task-definition \
                      --cli-input-json file://new-taskdef.json)

                  NEW_REV=$(echo "$REGISTERED" | jq -r '.taskDefinition.taskDefinitionArn')

                  echo "TASK_DEF_ARN=$NEW_REV" >> $GITHUB_ENV

            - name: Deploy new Task Definition to ECS Service
              run: |
                  aws ecs update-service \
                    --cluster $CLUSTER_NAME \
                    --service $SERVICE_NAME \
                    --task-definition $TASK_DEF_ARN \
                    --force-new-deployment

                  echo "Deployment triggered."
